5pm 3 open courses by dept
ucsb-cs156-w21/proj-ucsb-courses-search pull request #180
Opened 2021-03-02 20:34 UTC by J-Miller1

This pull request closes #171. Users can select a quarter and department and see all of the courses in that department and quarter that still have open seats as well as the number of open seats for each course.

The backend creates an aggregation pipeline to filter by courses with open seats in the selected department. The frontend displays this information in a table that can be sorted by any of the columns by clicking on that column's header.

Appropriate tests have also been introduced.

2021-03-02 22:07 UTC, dshamtob submitted a review, later dismissed

2021-03-03 03:08 UTC, jvoucsb requested changes

2021-03-03 03:40 UTC, WadeVaresio commented on javascript/src/main/components/Nav/AppNavbar.js
> +          <NavDropdown.Item as={Link} to="/statistics/numOpenCoursesByDept">
Hi Justin,

Thank you for bringing this to our attention, I inadvertently/mistakenly removed the item from the dropdown menu when resolving a merge conflict on my local machine.

I have added the item back to the dropdown menu.

2021-03-03 03:58 UTC, dshamtob approved these changes
Looks good.

2021-03-03 21:59 UTC, jvoucsb approved these changes
LGTM

2021-03-03 22:00 UTC, merged