5pm 4 ge download as csv
ucsb-cs156-w21/proj-ucsb-courses-search pull request #194
Opened 2021-03-03 21:06 UTC by codysasaki

2021-03-06 04:30 UTC, at527 approved these changes
LGTM

2021-03-06 04:59 UTC, at527 requested changes

2021-03-06 04:59 UTC, at527 commented on javascript/src/main/pages/History/Ge.js
> +    ]
Should it download all the displayed columns of the search? The deployment doesn't seem to do that.

2021-03-06 17:50 UTC, zminshall commented
Please add a description to this PR and link it to an issue. I am also interested in seeing more of the data added to the downloaded csv. Documentation for adding more columns available at https://www.npmjs.com/package/react-csv

2021-03-08 17:57 UTC, zminshall requested changes
This PR still needs a description and needs to be linked to an issue.

2021-03-08 21:05 UTC, closed without merging