5pm-b Backend Schedule Operations
ucsb-cs156-w21/proj-ucsb-courses-search pull request #80
Opened 2020-12-10 05:00 UTC by Mitchell57

This pull request adds entities for Schedule and ScheduleItem, as well as repositories, controllers, and tests for all new classes.

2020-12-10 09:28 UTC, pconrad commented
Please address merge conflicts, and get a team member's code review before staff review this

2020-12-10 09:30 UTC, pconrad commented
Please also remove `.DS_Store` files from this branch, and add `.DS_Store` to `.gitignore` before we review it.

2020-12-11 06:37 UTC, Mitchell57 commented
The only things not being tested are the onSuccess and onError declarations in the AddSchedForm and ScheduleSearchForm, but I'm not sure how to trigger those from the Schedule page

2020-12-11 06:47 UTC, seanaocostello reviewed
Looks good to me!

2020-12-11 06:55 UTC, andyyyho submitted a review, later dismissed
Looks good

2020-12-11 06:56 UTC, seanaocostello approved these changes

2020-12-11 06:56 UTC, seanaocostello submitted a review, later dismissed
Still looks good!

2020-12-11 23:02 UTC, pconrad requested changes
This PR deletes `javascript/.env.local.SAMPLE`, but that is a critical file.

That files needs to be restored before this is mergable.

2020-12-11 23:09 UTC, pconrad requested changes
secrets-heroku.properties.SAMPLE should not have been deleted

secrets-localhost.properties.SAMPLE should not have been deleted.

please restore these

2020-12-11 23:09 UTC, pconrad commented on docs/heroku.md
> +cp secrets-heroku.properties secrets-heroku.properties
This change is incorrect.     Please revert this change to the original

2020-12-11 23:09 UTC, pconrad commented on javascript/package-lock 2.json
> +{
This file should  not be checked into the code base.  Not sure why it exists.  Please remove

2020-12-11 23:09 UTC, pconrad commented on javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
> +//const buttonFormatter = (cell, row, rowIndex, formatExtraData) => {
Please remove the commented out code.

In general, commented out code should not be committed to main. Commenting out code is a strategy used during the development of code, but it should not end up in the final product.

2020-12-11 23:11 UTC, pconrad requested changes
Please remove all of the .DS_Store files that are part of this commit.

2021-02-22 23:48 UTC, mara-downing commented
Closing for now, linked in w21 issue #40 for students to reference.

2021-02-22 23:48 UTC, closed without merging